on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: fixerskubes1.azurecr.io
        username: ${{ secrets.acr_fixerskubes1_username }}
        password: ${{ secrets.acr_fixerskubes1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t fixerskubes1.azurecr.io/fixerkubecluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push fixerskubes1.azurecr.io/fixerkubecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_fixerkubecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep fixer-kube-clustera13f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace fixer-kube-clustera13f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: fixer-kube-clustera13f
        container-registry-url: fixerskubes1.azurecr.io
        container-registry-username: ${{ secrets.acr_fixerskubes1_username }}
        container-registry-password: ${{ secrets.acr_fixerskubes1_password }}
        secret-name: fixerkubecludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: fixer-kube-clustera13f
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          fixerskubes1.azurecr.io/fixerkubecluster:${{ github.sha }}
        imagepullsecrets: |
          fixerkubecludockerauth
